document.addEventListener("DOMContentLoaded",()=>{let e=document.querySelector("header h1");e.style.transition="transform 2s ease-in-out",e.style.transform="translateY(-100px)",setTimeout(()=>e.style.transform="translateY(0)",500);let t=document.querySelector("header p");t&&(t.style.transition="opacity 2s ease-in-out",t.style.opacity="0",setTimeout(()=>t.style.opacity="1",1e3));let s=document.getElementById("introduction");s.style.opacity="0",s.style.transition="opacity 2s ease-in-out",setTimeout(()=>s.style.opacity="1",1500);let a=document.querySelectorAll(".member");a.forEach(e=>{e.addEventListener("mouseenter",()=>{e.style.boxShadow="0 8px 16px rgba(0, 0, 0, 0.2)"}),e.addEventListener("mouseleave",()=>{e.style.boxShadow="0 4px 8px rgba(0, 0, 0, 0.1)"}),e.addEventListener("click",()=>{let t=e.querySelectorAll("p, .hobbies");t.forEach(e=>{e.style.display="none"===e.style.display?"block":"none"})});let t=e.querySelector("img");t.addEventListener("click",()=>{t.style.animation="shake 0.5s",t.addEventListener("animationend",()=>{t.style.animation=""})})});let l=document.querySelectorAll("section h2");l.forEach(e=>{e.style.transition="opacity 1s ease-in-out",e.style.opacity="0",setTimeout(()=>e.style.opacity="1",1e3)});let r=document.querySelectorAll(".hobbies h4");r.forEach(e=>{e.addEventListener("click",()=>{e.nextElementSibling.style.display="none"===e.nextElementSibling.style.display?"block":"none"})});let n=document.querySelectorAll("footer a");n.forEach(e=>{e.addEventListener("click",t=>{t.preventDefault(),document.querySelector(e.getAttribute("href")).scrollIntoView({behavior:"smooth"})})});let o=document.getElementById("nigerian-meals");o.style.opacity="0",o.style.transition="opacity 2s ease-in-out",setTimeout(()=>o.style.opacity="1",2e3);let i=document.querySelectorAll(".meal img");i.forEach(e=>{e.addEventListener("mouseenter",()=>{e.style.transform="scale(1.05)"}),e.addEventListener("mouseleave",()=>{e.style.transform="scale(1)"}),e.addEventListener("mouseenter",()=>{e.style.transition="transform 0.5s",e.style.transform="rotate(5deg) scale(1.05)"})}),l.forEach(e=>{e.addEventListener("mouseenter",()=>{e.style.transform="scale(1.1)"}),e.addEventListener("mouseleave",()=>{e.style.transform="scale(1)"})}),n.forEach(e=>{e.addEventListener("mouseenter",()=>{e.style.color="#ff6b6b"}),e.addEventListener("mouseleave",()=>{e.style.color="#6c63ff"})}),a.forEach(e=>{e.addEventListener("click",()=>{a.forEach(e=>e.classList.remove("highlight")),e.classList.add("highlight")})})});const style=document.createElement("style");style.innerHTML=`
    @keyframes shake {
      0% { transform: translateX(0); }
      25% { transform: translateX(-5px); }
      50% { transform: translateX(5px); }
      75% { transform: translateX(-5px); }
      100% { transform: translateX(0); }
    }
    .highlight {
      border: 2px solid #6c63ff;
    }
  `,document.head.appendChild(style);
